mi_blog/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

end

mi_blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

mi_blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
end

mi_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mi_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js #busca un archivo create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

mi_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == 'admin' && password == "secret"
      end
    end
end

mi_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

mi_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

mi_blog/app/helpers/posts_helper.rb
module PostsHelper
end

mi_blog/app/views/comments/_comment.html.erb
<%= div_for comment do %>
		<p>
			<strong>Posted
				<%= time_ago_in_words(comment.created_at) %>
			</strong><br/>
			<%= h(comment.body) %>
		</p>
<% end %>

mi_blog/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mi_blog/app/views/comments/comment.html.erb
<%= div_for comment do %>
		<p>
			<strong>Posted
				<%= time_ago_in_words(comment.created_at) %>
			</strong><br/>
			<%= h(comment.body) %>
		</p>
<% end %>

mi_blog/app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$("#comment_<%= @comment.id %>").fadeIn('slow');
$('#new_comment')[0].reset;

mi_blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

mi_blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

mi_blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

mi_blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

mi_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mi Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
   
</head>
<body>
<div class="container">
<h1 class="jumbotron">El blog del programador perdido</h1>
<nav class="navbar navbar-default" role="navigation">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="index.html">Inicio</a>
				</div>
			
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav">
						
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Trabajos <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="http://www.elmundo.es/grafico/economia/2014/10/01/542c442a268e3ee96c8b457c.html">Las cifras del paro</a></li>
                        		<li><a href="http://www.elmundo.es/grafico/economia/2014/10/24/544a3a98268e3ece028b456d.html">Evolución histórica del paro</a></li>
                        		<li><a href="http://www.elmundo.es/grafico/espana/2014/11/03/5453d2e6268e3e8d7f8b456c.html">El mapa de la corrupci&oacute;n</a></li>
							</ul>
						</li>
						<li class=""><a href="monte.html">M&eacute;todo Montecarlo</a></li>
						<li class="active"><a href="blog.html">Blog</a></li>
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						<li><a href="" data-toggle="modal" data-target="#myModal">Contacto</a></li>
						
					</ul>
				</div><!-- /.navbar-collapse -->
			</nav>
<%= yield %>
    <!--Ventana de dialogo que se abre cuando pulsamos el enlace de contacto-->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModal-label">Contacto</h4>
                </div>
                <div class="modal-body">
                    <form action="mail.php" method="post" role="form" class="form-horizontal">
				
			
				<div class="form-group has-feedback">
					<label for="email" class="control-label col-md-3">Email</label>
					<div class="col-md-6">
					<input type="email" class="form-control" id="" placeholder="input your email" name="mail" required="required">
					<span class="form-control-feedback glyphicon "></span>
					</div>
				</div>
				<div class="form-group has-feedback">
					<label for="comentario" class="control-label col-md-3">Comentario</label>
					<div class="col-md-6">
						<div class="input-group">
							
							<input class="form-control" type="textarea" name="comentario" required="required" id="coment"> </input>
							
						</div>
						<span class="glyphicon form-control-feedback"></span>
					</div>
				</div>
				
			
				<button type="submit" class="btn btn-primary" id="register">Enviar</button>
			</form>
                </div>
                <div class="modal-footer">
                                    <div class="alert alert-success hidden" id="alerta-correcto">
				<!--Alert-->
				<h2>Saved data</h2>
				<div>Your information has been submitted</div>
			</div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

                </div>
            </div>

        </div>
    </div>	
<!-- jQuery -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</div>
</body>
</html>

mi_blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mi_blog/app/views/posts/edit.html.erb
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<h2>Editar comentario</h2>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<%= render 'form' %>
	</div>
	<div class="col-md-2"></div>
</div>


<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-2">
				<%= link_to 'Ver', @post %>
			</div>
			<div class="col-md-10">
				<%= link_to 'Volver', posts_path %>
			</div>
		</div>
		
		
	</div>
	<div class="col-md-2"></div>
</div>

mi_blog/app/views/posts/index.html.erb
      <div class="row">
        <p id="notice"><%= notice %></p>


</div>
<div class="row">
  

    <% @posts.each do |post| %>
     
        <div class="tituloPost col-md-offset-2 col-md-10"><h2><%= post.title %></h2></div>
        <div class="cuerpoPost col-md-offset-2 col-md-8"><%= post.body %></div>
</div>
<div class="row">
<div class="col-md-offset-2">
        <%= link_to 'Ver', post %>
        <%= link_to 'Editar', edit_post_path(post) %>
        <%= link_to 'Borrar', post, method: :delete, data: { confirm: '¿Estás seguro?' } %></div>
   
    <% end %>
 </div>




<div class="row">
  <%= link_to 'Nuevo post', new_post_path %>
</div>


      

  

    

mi_blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

mi_blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<h2><%= @post.title %></h2>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="cuerpoPost col-md-8">
		<%= @post.body %>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<h2>Comentarios</h2>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8" id="comments">
	<%= render :partial => @post.comments.reverse %>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<%= form_for([@post, Comment.new], remote: true) do |f| %>
<p>
	<%= f.label :body, "Nuevo comentario"%><br>
	<%= f.text_area :body %>
</p>
<p>
	<%= f.submit "Añade comentario" %>
</p>
<% end %>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-2">
				<%= link_to 'Edit', edit_post_path(@post) %>
			</div>
			<div class="col-md-10">
				<%= link_to 'Back', posts_path %>
			</div>
		</div>
		
		
	</div>
	<div class="col-md-2"></div>
</div>